export const PRESIDENTIAL_CANDIDATES = [
  {
    id: 1,
    slug: 'william-ruto',
    name: 'William Samoei Ruto',
    nickname: 'Hustler President',
    position: 'Presidential Candidate',
    party: 'United Democratic Alliance (UDA)',
    partyShortname: 'UDA',
    partyColor: '#FF6B00',
    constituency: 'Sugoi, Uasin Gishu County',
    county: 'Uasin Gishu',
    region: 'Rift Valley',
    currentPosition: '5th President of the Republic of Kenya',
    email: 'president@statehouse.go.ke',
    phone: '+254 202 227 411',
    status: 'announced',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/William_Ruto_official_portrait.jpg/800px-William_Ruto_official_portrait.jpg',
    verified: true,
    tags: ['incumbent', 'president', 'hustler-nation'],
    previousPositions: [
      'Deputy President of Kenya (2013–2022)',
      'Minister for Agriculture (2008–2010)',
      'Member of Parliament, Eldoret North (1997–2013)',
    ],
    achievements: [
      'Launched the Bottom-Up Economic Transformation Agenda (BETA)',
      'Established the Hustler Fund providing affordable credit to citizens',
      'Implemented Affordable Housing Programme across Kenya',
      'Launched Universal Health Coverage (UHC) programme',
      'Introduced CBC curriculum reforms in education',
    ],
    manifesto: "The Bottom-Up Economic Transformation Agenda focuses on empowering ordinary Kenyans through affordable credit, housing, agriculture, SME support, and digital economy. The plan targets the bottom 80% of Kenyans through the Hustler Fund, affordable housing, universal health coverage, and job creation for youth.",
    biography: "William Samoei Ruto was born on December 21, 1966, in Kamagut, Uasin Gishu County. He studied at University of Nairobi. He rose through grassroots politics and became Kenya's 5th President in September 2022.",
    education: ['University of Nairobi - BSc Botany/Zoology', 'University of Nairobi - MSc Biology', 'University of Nairobi - PhD Plant Ecology'],
    socialMedia: {
      twitter: 'WilliamsRuto',
      facebook: 'williamsamoeiruto',
    },
  },
  {
    id: 2,
    slug: 'rigathi-gachagua',
    name: 'Rigathi Gachagua',
    nickname: 'Ichungwa',
    position: 'Presidential Candidate',
    party: 'Democracy for Citizens Party (DCP)',
    partyShortname: 'DCP',
    partyColor: '#0099CC',
    constituency: 'Mathira, Nyeri County',
    county: 'Nyeri',
    region: 'Central Kenya',
    currentPosition: 'Former Deputy President of Kenya',
    email: 'info@rigathi.co.ke',
    phone: '+254 722 000 000',
    status: 'announced',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Rigathi_Gachagua.jpg/800px-Rigathi_Gachagua.jpg',
    verified: true,
    tags: ['former-dp', 'central-kenya', 'ichungwa'],
    previousPositions: [
      'Deputy President of Kenya (2022–2023)',
      'Member of Parliament, Mathira (2013–2022)',
      'Presidential Advisor under Mwai Kibaki',
    ],
    achievements: [
      'Championed regional balance in government appointments',
      'Advocated for Mt Kenya economic interests',
      'Spearheaded anti-corruption initiatives during tenure as DP',
    ],
    manifesto: "A Kenya where every community has equal representation. Gachagua champions regional balance, equity in resource allocation, and grassroots economic empowerment across all 47 counties.",
    biography: "Rigathi Gachagua was born in 1965 in Mathira, Nyeri County. He served as Kenya's Deputy President from 2022 until his historic impeachment in October 2023. He remains a powerful political figure in Mount Kenya region.",
    education: ['University of Nairobi - Political Science', 'Kenya School of Law'],
    socialMedia: {
      twitter: 'GachaguaRigathi',
      facebook: 'GachaguaRigathi',
    },
  },
  {
    id: 3,
    slug: 'edwin-sifuna',
    name: 'Edwin Sifuna',
    nickname: 'The People\'s Voice',
    position: 'Presidential Candidate',
    party: 'Orange Democratic Movement (ODM)',
    partyShortname: 'ODM',
    partyColor: '#FF8C00',
    constituency: 'Nairobi County',
    county: 'Nairobi',
    region: 'Nairobi',
    currentPosition: 'ODM Secretary General & Nairobi Senator',
    email: 'sifuna@odm.co.ke',
    phone: '+254 700 000 001',
    status: 'exploring',
    image: 'https://images.standardmedia.co.ke/images/wednesday/1200x/23022022125200.jpg',
    verified: true,
    tags: ['odm', 'senator', 'nairobi', 'youth-champion'],
    previousPositions: [
      'Nairobi County Senator (2017–present)',
      'ODM Secretary General',
      'Lawyer and Political Commentator',
    ],
    achievements: [
      'Championed youth empowerment legislation in Senate',
      'Led ODM party reorganization efforts',
      'Consistent advocate for anti-corruption measures',
      'Vocal defender of constitutional rights',
    ],
    manifesto: "Transforming Kenya through inclusive governance, youth employment, free education, and restructuring of devolution to ensure every shilling reaches the grassroots.",
    biography: "Edwin Sifuna is a lawyer, politician, and senator for Nairobi County. Known for his charismatic public speaking and sharp political commentary, he has emerged as a leading voice of the youth generation in Kenyan politics.",
    education: ['University of Nairobi - LLB', 'Kenya School of Law - Advocate'],
    socialMedia: {
      twitter: 'edwinsifuna',
      facebook: 'SifunaEdwin',
    },
  },
  {
    id: 4,
    slug: 'kalonzo-musyoka',
    name: 'Kalonzo Musyoka',
    nickname: 'The Kingmaker',
    position: 'Presidential Candidate',
    party: 'Wiper Democratic Movement',
    partyShortname: 'Wiper',
    partyColor: '#8B0000',
    constituency: 'Mwingi North, Kitui County',
    county: 'Kitui',
    region: 'Eastern Kenya',
    currentPosition: 'Wiper Party Leader',
    email: 'kalonzo@wiper.co.ke',
    phone: '+254 722 000 002',
    status: 'announced',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Kalonzo_Musyoka.jpg/800px-Kalonzo_Musyoka.jpg',
    verified: true,
    tags: ['wiper', 'veteran', 'eastern-kenya', 'azimio'],
    previousPositions: [
      'Vice President of Kenya (2008–2013)',
      'Presidential Candidate (2007, 2013, 2017, 2022)',
      'Minister of Foreign Affairs',
      'Member of Parliament, Mwingi North',
    ],
    achievements: [
      'Served as Vice President under Mwai Kibaki',
      'Played key role in Kenyan peacekeeping in South Sudan',
      'Decades of service in public office since 1985',
      'Consistent human rights and democracy advocate',
    ],
    manifesto: "Building a united Kenya based on the rule of law, national cohesion, equitable resource distribution, and restoration of institutional integrity. Kalonzo brings decades of governance experience.",
    biography: "Stephen Kalonzo Musyoka was born on December 24, 1953. He has been a central figure in Kenyan politics for over 40 years, having served as VP, presidential candidate multiple times, and consistent coalition builder.",
    education: ['University of Nairobi - Law Degree', 'Nairobi School', 'Catholic University of Eastern Africa - Honorary'],
    socialMedia: {
      twitter: 'kalmusyoka',
      facebook: 'KalonzoMusyoka',
    },
  },
  {
    id: 5,
    slug: 'fred-matiangi',
    name: 'Fred Okengo Matiangi',
    nickname: 'The Enforcer',
    position: 'Presidential Candidate',
    party: 'Independent / Forming Coalition',
    partyShortname: 'IND',
    partyColor: '#2E4057',
    constituency: 'Bobasi, Kisii County',
    county: 'Kisii',
    region: 'Nyanza',
    currentPosition: 'Former Cabinet Secretary & Presidential Candidate',
    email: 'matiangi2027@gmail.com',
    phone: '+254 722 000 003',
    status: 'announced',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Fred_Matiang%27i.jpg/800px-Fred_Matiang%27i.jpg',
    verified: true,
    tags: ['former-cs', 'security', 'education-reforms', 'kisii'],
    previousPositions: [
      'Cabinet Secretary for Interior & Coordination of National Government',
      'Cabinet Secretary for Education',
      'Cabinet Secretary for ICT',
      'Coordinator of National Government (2017–2022)',
    ],
    achievements: [
      'Reformed KCSE exams eliminating mass cheating',
      'Led security crackdown reducing crime rates significantly',
      'Digitized government services in Kenya',
      'Coordinated COVID-19 government response',
    ],
    manifesto: "Restoring institutions, fighting corruption decisively, and building a security-first Kenya where rule of law reigns supreme. Matiangi's technocratic leadership model prioritizes efficiency and accountability in government.",
    biography: "Fred Matiangi is known as one of Kenya's most efficient administrators. As CS for Education, he revolutionized national examinations. As Interior CS, he was feared for his no-nonsense approach to security.",
    education: ['Egerton University - BA', 'University of Reading UK - PhD Communication'],
    socialMedia: {
      twitter: 'FredMatiangi',
      facebook: 'fredmatiangi',
    },
  },
  {
    id: 6,
    slug: 'george-wajackoyah',
    name: 'Prof. George Luchiri Wajackoyah',
    nickname: 'Roots Man',
    position: 'Presidential Candidate',
    party: 'Roots Party of Kenya',
    partyShortname: 'Roots',
    partyColor: '#2D6A2D',
    constituency: 'Nairobi',
    county: 'Nairobi',
    region: 'Nairobi',
    currentPosition: 'Roots Party Leader & International Lawyer',
    email: 'wajackoyah@rootsparty.co.ke',
    phone: '+254 722 000 004',
    status: 'announced',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/George_Wajackoyah.jpg/800px-George_Wajackoyah.jpg',
    verified: true,
    tags: ['roots-party', 'marijuana', 'alternative', 'unconventional'],
    previousPositions: [
      '2022 Presidential Candidate (scored 5th)',
      'Interpol Officer (UK)',
      'CIA Special Agent (alleged)',
      'International Lawyer',
    ],
    achievements: [
      'Challenged mainstream politics with fresh alternative narrative',
      'Rallied massive youth following in 2022 elections',
      'Advocate for marijuana legalization as economic policy',
      'International law and human rights expertise',
    ],
    manifesto: "Kenya Rising: Leveraging cannabis farming for national debt repayment, eliminating corruption through radical transparency, empowering youth entrepreneurs, and building a fair justice system.",
    biography: "Prof. George Wajackoyah is Kenya's most colourful political figure. A lawyer, former law enforcement officer, and academic, he shocked Kenyans in 2022 with his marijuana legalization platform and energized youth support.",
    education: ['University of Wolverhampton - LLB', 'University of Wales - LLM', 'Walden University - PhD'],
    socialMedia: {
      twitter: 'wajackoyah_g',
      facebook: 'WajackoyahGeorge',
    },
  },
  {
    id: 7,
    slug: 'david-maraga',
    name: 'David Kenani Maraga',
    nickname: 'The Just Judge',
    position: 'Presidential Candidate',
    party: 'Independent',
    partyShortname: 'IND',
    partyColor: '#1B4F72',
    constituency: 'Kisii County',
    county: 'Kisii',
    region: 'Nyanza',
    currentPosition: 'Former Chief Justice of Kenya',
    email: 'maraga2027@gmail.com',
    phone: '+254 722 000 005',
    status: 'exploring',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Justice_David_Maraga.jpg/800px-Justice_David_Maraga.jpg',
    verified: true,
    tags: ['former-cj', 'judiciary', 'rule-of-law', 'integrity'],
    previousPositions: [
      'Chief Justice of Kenya (2016–2021)',
      'Judge of Appeal – Court of Appeal',
      'Judge – High Court of Kenya',
      'Practicing Advocate',
    ],
    achievements: [
      'Led Supreme Court nullification of 2017 presidential election results',
      'Championed judicial independence against executive pressure',
      'Transformed Kenya\'s judicial system for efficiency',
      'Upheld the constitution against illegal government actions',
    ],
    manifesto: "Justice for All Kenyans: A presidency grounded in constitutional supremacy, zero tolerance for corruption, independent institutions, and restoration of public trust in government through transparency and accountability.",
    biography: "David Maraga is widely respected as the most fearless chief justice in Kenya's history. His landmark ruling nullifying the 2017 election placed him among Africa's most courageous judicial figures.",
    education: ['University of Nairobi - LLB', 'Kenya School of Law - Advocate', 'Various Judicial Training Programs'],
    socialMedia: {
      twitter: 'DKMaraga',
      facebook: 'DavidMaragaOfficial',
    },
  },
  {
    id: 8,
    slug: 'boniface-mwangi',
    name: 'Boniface Mwangi',
    nickname: 'Kenya\'s Rebel',
    position: 'Presidential Candidate',
    party: 'PAWA254 / Independent',
    partyShortname: 'PAWA',
    partyColor: '#E74C3C',
    constituency: 'Starehe, Nairobi',
    county: 'Nairobi',
    region: 'Nairobi',
    currentPosition: 'Activist, Photojournalist & Political Aspirant',
    email: 'boniface@pawa254.org',
    phone: '+254 722 000 006',
    status: 'announced',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Boniface_Mwangi.jpg/800px-Boniface_Mwangi.jpg',
    verified: true,
    tags: ['activist', 'youth', 'anti-corruption', 'genz', 'rebel'],
    previousPositions: [
      'Award-winning Photojournalist',
      'Founder of PAWA254 Art Space',
      'Parliamentary Candidate, Starehe 2017',
      'CNN Hero nominee',
    ],
    achievements: [
      'Founded PAWA254 youth civic space',
      'Multiple international journalism awards',
      'Led peaceful anti-corruption protests',
      'Exposed police brutality through photojournalism',
      'Partnered with Gen Z movements for change',
    ],
    manifesto: "A radical transformation of Kenya's political culture — ending impunity, creating a youth-centered economy, housing rights for all, police accountability, and building a truly democratic Kenya from the grassroots up.",
    biography: "Boniface Mwangi began as a photojournalist capturing post-election violence in 2007-08. He became one of Kenya's most recognized activists, founding PAWA254 and leading youth-centered civic movements.",
    education: ['Journalism & Photography', 'Columbia University - Visiting Fellow', 'World Press Photo Award Winner'],
    socialMedia: {
      twitter: 'bonifacemwangi',
      facebook: 'bonifacemwangiphotography',
    },
  },
  {
    id: 9,
    slug: 'martha-karua',
    name: 'Martha Wangari Karua',
    nickname: 'Iron Lady',
    position: 'Presidential Candidate',
    party: 'Narc Kenya / Azimio Alliance',
    partyShortname: 'NARC-K',
    partyColor: '#8E44AD',
    constituency: 'Gichugu, Kirinyaga County',
    county: 'Kirinyaga',
    region: 'Central Kenya',
    currentPosition: 'Lawyer, Politician & Former Minister',
    email: 'martha@narck.co.ke',
    phone: '+254 722 000 007',
    status: 'announced',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Martha_Karua.jpg/800px-Martha_Karua.jpg',
    verified: true,
    tags: ['iron-lady', 'azimio', 'women-leader', 'central-kenya', 'former-vp-candidate'],
    previousPositions: [
      'Running Mate to Raila Odinga – 2022 Presidential Election',
      'Minister of Justice and Constitutional Affairs (2003–2009)',
      'Member of Parliament, Gichugu (1992–2013)',
      'Narc Kenya Party Leader',
    ],
    achievements: [
      'First woman VP running mate in Kenya\'s history (2022)',
      'Led constitutional and justice reforms',
      'Championed women\'s rights in politics and law',
      'Decades of principled opposition to corruption',
      'Founding member of Kenya\'s democratic movement',
    ],
    manifesto: "Women, Youth, Justice: A Kenya where every citizen has a voice, gender equality is real, institutions serve the people, and public resources are managed with integrity and transparency.",
    biography: "Martha Karua is Kenya's Iron Lady — a lawyer and politician who has fought for justice and democratic space for over three decades. She was the first woman nominated as a running mate for a major Kenyan presidential ticket.",
    education: ['University of Nairobi - LLB', 'Kenya School of Law - Advocate', 'Various Legal Fellowship Programs'],
    socialMedia: {
      twitter: 'MarthaKarua',
      facebook: 'MarthaKaruaOfficial',
    },
  },
]

export const LEADERSHIP_POSITIONS = [
  'Presidential Candidate',
  'Governor',
  'Senator',
  'Member of Parliament',
  'Deputy Governor',
  'Woman Representative',
  'County Assembly Member',
]

export const getCandidate = (slug) =>
  PRESIDENTIAL_CANDIDATES.find((c) => c.slug === slug)

export const getCandidateById = (id) =>
  PRESIDENTIAL_CANDIDATES.find((c) => c.id === parseInt(id))
